dist: xenial
language: python
python:
  - 3.8
services:
  - postgresql
before_install:
  - sudo apt-get update
  - sudo apt-get install libevent-dev daemontools
  - wget https://chromedriver.storage.googleapis.com/99.0.4844.51/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - wget https://downloads.lambdatest.com/tunnel/linux/64bit/LT_Linux.zip
  - unzip LT_Linux.zip
  - ls
  - export CHROME_BIN=chromium-browser
  - export DJANGO_SETTINGS_MODULE=django_react.settings
  - export PYTHONPATH=$HOME/builds/caiodotdev/helpmusician
  - export PIP_USE_MIRRORS=true
  - psql -c 'CREATE DATABASE travisci;' -U postgres
  - export LT_USERNAME=caio.barbosa
  - export LT_ACCESS_KEY=NaNNdBDJGhzbKMsigjJ2213wRT75vQDYqxtc9m7miNzzvMqV4P
install:
  - pip install -U pip wheel
  - pip install -r requirements.txt
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py collectstatic
before_script:
  - python manage.py violations
script:
  - ./LT  --user caio.barbosa@virtus.ufcg.edu.br --key NaNNdBDJGhzbKMsigjJ2213wRT75vQDYqxtc9m7miNzzvMqV4P
  - python manage.py test
cache: pip
addons:
  browserstack:
    username: "caiodotdev_irwadE"
    access_key: "Ke15XkyiQ6qp9XryA26w"

env:
  global:
    - LT_USERNAME=${LAMBDATEST_USERNAME}
    - LT_ACCESS_KEY=${LAMBDATEST_ACCESS_KEY}
