dist: xenial
language: python
python:
  - 3.8
services:
  - postgresql
before_install:
  - sudo apt-get update
  - sudo apt-get install libevent-dev daemontools
  - export DJANGO_SETTINGS_MODULE=django_react.settings
  - export PYTHONPATH=$HOME/builds/caiodotdev/helpmusician
  - export PIP_USE_MIRRORS=true
  - psql -c 'CREATE DATABASE travisci;' -U postgres
install:
  - pip install -U pip wheel
  - pip install -r requirements.txt
  - python manage.py makemigrations
  - python manage.py migrate
before_script:
  - python manage.py violations
script:
  - python manage.py test
cache: pip
