dist: xenial
language: python
python:
  - 3.8
services:
  - postgresql
before_install:
  - sudo apt-get update
  - sudo apt-get install libevent-dev daemontools
  - wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python2.7.12/bin/
  - export CHROME_BIN=chromium-browser
  - export DJANGO_SETTINGS_MODULE=django_react.settings
  - export PYTHONPATH=$HOME/builds/caiodotdev/helpmusician
  - export PIP_USE_MIRRORS=true
  - psql -c 'CREATE DATABASE travisci;' -U postgres
install:
  - pip install -U pip wheel
  - pip install -r requirements.txt
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py collectstatic
before_script:
  - python manage.py violations
script:
  - python manage.py test
cache: pip
addons:
  browserstack:
    username: "caiodotdev_irwadE"
    access_key: "Ke15XkyiQ6qp9XryA26w"
