# Generated by Django 3.2.12 on 2022-04-03 18:56

import app.models
import app.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, max_length=255, null=True, upload_to=app.models.source_file_path, validators=[app.validators.is_valid_size, app.validators.is_valid_audio_file])),
                ('file_url', models.URLField(blank=True, null=True)),
                ('filename', models.TextField(blank=True, null=True)),
                ('path_on_dropbox', models.TextField(blank=True, null=True)),
                ('is_youtube', models.BooleanField(default=False)),
                ('youtube_link', models.URLField(blank=True, null=True, unique=True, validators=[app.validators.is_valid_youtube])),
            ],
        ),
        migrations.CreateModel(
            name='SourceTrack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artist', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('tone', models.CharField(blank=True, max_length=10, null=True)),
                ('bpm', models.CharField(blank=True, max_length=10, null=True)),
                ('bar_length', models.CharField(blank=True, max_length=10, null=True)),
                ('chords', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sourcefile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='YTAudioDownloadTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('celery_id', models.UUIDField(blank=True, default=None, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Queued'), (1, 'In Progress'), (2, 'Done'), (-1, 'Error')], default=0)),
                ('error', models.TextField(blank=True)),
                ('date_finished', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='sourcefile',
            name='youtube_fetch_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ytaudiodownloadtask'),
        ),
        migrations.CreateModel(
            name='StaticMix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('celery_id', models.UUIDField(blank=True, default=None, null=True)),
                ('separator', models.CharField(default='spleeter', max_length=20)),
                ('separator_args', picklefield.fields.PickledObjectField(default=dict, editable=False)),
                ('bitrate', models.IntegerField(choices=[(192, 'Mp3 192'), (256, 'Mp3 256'), (320, 'Mp3 320')], default=256)),
                ('vocals', models.BooleanField()),
                ('piano', models.BooleanField()),
                ('drums', models.BooleanField()),
                ('bass', models.BooleanField()),
                ('other', models.BooleanField()),
                ('status', models.IntegerField(choices=[(0, 'Queued'), (1, 'In Progress'), (2, 'Done'), (-1, 'Error')], default=0)),
                ('file', models.FileField(blank=True, max_length=255, upload_to=app.models.mix_track_path)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('filename', models.TextField(blank=True, null=True)),
                ('path_on_dropbox', models.TextField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_finished', models.DateTimeField(blank=True, default=None, null=True)),
                ('source_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='static', to='app.sourcetrack')),
            ],
            options={
                'unique_together': {('source_track', 'separator', 'separator_args', 'bitrate', 'vocals', 'piano', 'drums', 'bass', 'other')},
            },
        ),
        migrations.CreateModel(
            name='DynamicMix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('celery_id', models.UUIDField(blank=True, default=None, null=True)),
                ('separator', models.CharField(default='spleeter', max_length=20)),
                ('separator_args', picklefield.fields.PickledObjectField(default=dict, editable=False)),
                ('bitrate', models.IntegerField(choices=[(192, 'Mp3 192'), (256, 'Mp3 256'), (320, 'Mp3 320')], default=256)),
                ('folder_path_on_dropbox', models.TextField(blank=True, null=True)),
                ('vocals_file', models.FileField(blank=True, max_length=255, upload_to=app.models.mix_track_path)),
                ('vocals_url', models.URLField(blank=True, null=True)),
                ('vocals_path', models.TextField(blank=True, null=True)),
                ('piano_file', models.FileField(blank=True, max_length=255, upload_to=app.models.mix_track_path)),
                ('piano_url', models.URLField(blank=True, null=True)),
                ('piano_path', models.TextField(blank=True, null=True)),
                ('other_file', models.FileField(blank=True, max_length=255, upload_to=app.models.mix_track_path)),
                ('other_url', models.URLField(blank=True, null=True)),
                ('other_path', models.TextField(blank=True, null=True)),
                ('bass_file', models.FileField(blank=True, max_length=255, upload_to=app.models.mix_track_path)),
                ('bass_url', models.URLField(blank=True, null=True)),
                ('bass_path', models.TextField(blank=True, null=True)),
                ('drums_file', models.FileField(blank=True, max_length=255, upload_to=app.models.mix_track_path)),
                ('drums_url', models.URLField(blank=True, null=True)),
                ('drums_path', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Queued'), (1, 'In Progress'), (2, 'Done'), (-1, 'Error')], default=0)),
                ('error', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_finished', models.DateTimeField(blank=True, default=None, null=True)),
                ('source_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic', to='app.sourcetrack')),
            ],
            options={
                'unique_together': {('source_track', 'separator', 'separator_args', 'bitrate')},
            },
        ),
    ]
