# Generated by Django 3.1.7 on 2022-03-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('chordInfo', models.CharField(blank=True, max_length=255, null=True)),
                ('derivedKey', models.CharField(blank=True, max_length=255, null=True)),
                ('derivedBpm', models.CharField(blank=True, max_length=255, null=True)),
                ('barLength', models.CharField(blank=True, max_length=255, null=True)),
                ('versionId', models.CharField(blank=True, max_length=255, null=True)),
                ('chords', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
