# Generated by Django 3.2.12 on 2022-04-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_sourcetrack_source_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcetrack',
            name='thumb',
            field=models.URLField(blank=True, null=True),
        ),
    ]
