# Generated by Django 3.2.12 on 2022-04-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_sourcetrack_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicmix',
            name='bass_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dynamicmix',
            name='bass_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dynamicmix',
            name='drums_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dynamicmix',
            name='drums_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dynamicmix',
            name='other_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dynamicmix',
            name='other_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dynamicmix',
            name='piano_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dynamicmix',
            name='piano_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dynamicmix',
            name='vocals_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dynamicmix',
            name='vocals_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sourcefile',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sourcefile',
            name='public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='staticmix',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staticmix',
            name='public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
