# Generated by Django 3.2.12 on 2022-04-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220411_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicmix',
            name='bass_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dynamicmix',
            name='drums_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dynamicmix',
            name='other_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dynamicmix',
            name='piano_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dynamicmix',
            name='vocals_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sourcefile',
            name='file_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staticmix',
            name='file_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
