# Generated by Django 3.1.7 on 2022-03-22 16:13

from django.db import migrations, models
import django.db.models.deletion
import frontend.models
import frontend.validators
import picklefield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, max_length=255, null=True, upload_to=frontend.models.source_file_path, validators=[frontend.validators.is_valid_size, frontend.validators.is_valid_audio_file])),
                ('is_youtube', models.BooleanField(default=False)),
                ('youtube_link', models.URLField(blank=True, null=True, unique=True, validators=[frontend.validators.is_valid_youtube])),
            ],
        ),
        migrations.CreateModel(
            name='SourceTrack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artist', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('source_file', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.sourcefile')),
            ],
        ),
        migrations.CreateModel(
            name='YTAudioDownloadTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('celery_id', models.UUIDField(blank=True, default=None, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Queued'), (1, 'In Progress'), (2, 'Done'), (-1, 'Error')], default=0)),
                ('error', models.TextField(blank=True)),
                ('date_finished', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='sourcefile',
            name='youtube_fetch_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.ytaudiodownloadtask'),
        ),
        migrations.CreateModel(
            name='StaticMix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('celery_id', models.UUIDField(blank=True, default=None, null=True)),
                ('separator', models.CharField(default='spleeter', max_length=20)),
                ('separator_args', picklefield.fields.PickledObjectField(default=dict, editable=False)),
                ('bitrate', models.IntegerField(choices=[(192, 'Mp3 192'), (256, 'Mp3 256'), (320, 'Mp3 320')], default=256)),
                ('vocals', models.BooleanField()),
                ('piano', models.BooleanField()),
                ('drums', models.BooleanField()),
                ('bass', models.BooleanField()),
                ('other', models.BooleanField()),
                ('status', models.IntegerField(choices=[(0, 'Queued'), (1, 'In Progress'), (2, 'Done'), (-1, 'Error')], default=0)),
                ('file', models.FileField(blank=True, max_length=255, upload_to=frontend.models.mix_track_path)),
                ('error', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_finished', models.DateTimeField(blank=True, default=None, null=True)),
                ('source_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='static', to='frontend.sourcetrack')),
            ],
            options={
                'unique_together': {('source_track', 'separator', 'separator_args', 'bitrate', 'vocals', 'piano', 'drums', 'bass', 'other')},
            },
        ),
        migrations.CreateModel(
            name='DynamicMix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('celery_id', models.UUIDField(blank=True, default=None, null=True)),
                ('separator', models.CharField(default='spleeter', max_length=20)),
                ('separator_args', picklefield.fields.PickledObjectField(default=dict, editable=False)),
                ('bitrate', models.IntegerField(choices=[(192, 'Mp3 192'), (256, 'Mp3 256'), (320, 'Mp3 320')], default=256)),
                ('vocals_file', models.FileField(blank=True, max_length=255, upload_to=frontend.models.mix_track_path)),
                ('piano_file', models.FileField(blank=True, max_length=255, upload_to=frontend.models.mix_track_path)),
                ('other_file', models.FileField(blank=True, max_length=255, upload_to=frontend.models.mix_track_path)),
                ('bass_file', models.FileField(blank=True, max_length=255, upload_to=frontend.models.mix_track_path)),
                ('drums_file', models.FileField(blank=True, max_length=255, upload_to=frontend.models.mix_track_path)),
                ('status', models.IntegerField(choices=[(0, 'Queued'), (1, 'In Progress'), (2, 'Done'), (-1, 'Error')], default=0)),
                ('error', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_finished', models.DateTimeField(blank=True, default=None, null=True)),
                ('source_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic', to='frontend.sourcetrack')),
            ],
            options={
                'unique_together': {('source_track', 'separator', 'separator_args', 'bitrate')},
            },
        ),
    ]
