# Generated by Django 3.1.7 on 2022-03-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcefile',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
