# Generated by Django 4.0.3 on 2022-03-24 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0002_sourcefile_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcetrack',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staticmix',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
