# Generated by Selenium IDE
import time

from django.contrib.auth.models import User
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait

from app.tests.base import BaseLoggedSeleniumTestCase
from app.tests.constants import USERNAME_USER_DEFAULT
from app.tests.utils import create_sourcetrack_dynamicmix, delete_track_and_mix


class TestPlayaudiomixer(BaseLoggedSeleniumTestCase):

    def test_playaudio(self):
        print('Test Play Audio on Media Player')
        time.sleep(1)
        assert self.driver.find_element(By.LINK_TEXT, "Original").text == "Original"
        self.driver.find_element(By.LINK_TEXT, "Original").click()
        WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.LINK_TEXT, "Voltar")))
        time.sleep(2)
        elements = self.driver.find_elements(By.ID, "play")
        assert len(elements) > 0
        elements = self.driver.find_elements(By.LINK_TEXT, "Download")
        assert len(elements) > 0
        elements = self.driver.find_elements(By.LINK_TEXT, "Voltar")
        assert len(elements) > 0
        self.driver.find_element(By.CSS_SELECTOR, "#content > .col-12").click()
        elements = self.driver.find_elements(By.ID, "player_range")
        assert len(elements) > 0
