# Generated by Selenium IDE
import time

from django.contrib.auth.models import User
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait

from app.tests.base import BaseLoggedSeleniumTestCase
from app.tests.constants import USERNAME_USER_DEFAULT
from app.tests.utils import create_sourcetrack_dynamicmix, delete_track_and_mix


class TestMixer(BaseLoggedSeleniumTestCase):

    def test_mixer(self):
        print('Test Mixer Page')
        time.sleep(1)
        elements = self.driver.find_elements(By.CSS_SELECTOR, "tr:nth-child(1) .btn-danger > .fa")
        assert len(elements) > 0
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) .btn-success > .fa").click()
        WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.ID, "play")))
        time.sleep(2)
        elements = self.driver.find_elements(By.ID, "play")
        assert len(elements) > 0
        WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.ID, "player_range")))
        self.driver.find_element(By.CSS_SELECTOR, "h2").click()
        assert self.driver.find_element(By.CSS_SELECTOR, "h2").text == "Mixer"
