# Generated by Selenium IDE
import time

from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys

from app.tests.base import BaseLoggedSeleniumTestCase


class TestDownloadmusicyoutube(BaseLoggedSeleniumTestCase):

    def test_downloadmusicyoutube(self):
        self.logger.debug('Test Download Music from youtube and confirm')
        self.driver.set_window_size(1382, 744)
        self.driver.find_element(By.ID, "search").click()
        self.driver.find_element(By.ID, "search").send_keys("gabriela rocha")
        self.driver.find_element(By.CSS_SELECTOR, ".lead").click()
        assert self.driver.find_element(By.ID, "search_btn").text == "Buscar"
        self.driver.find_element(By.ID, "search_btn").click()
        self.driver.find_element(By.CSS_SELECTOR, ".col-12:nth-child(1) .card-img-top").click()
        self.driver.find_element_by_tag_name('html').send_keys(Keys.END)
        assert self.driver.find_element(By.ID, "search").text == "Confirmar"
        # self.driver.find_element(By.ID, "search").click()
        # time.sleep(3)
        # assert self.driver.find_element(By.CSS_SELECTOR, "h2:nth-child(6)").text == "Sucesso"
        # self.driver.find_element(By.CSS_SELECTOR, ".confirm").click()
