# Generated by Selenium IDE
import time

from selenium import webdriver
from selenium.webdriver.common.by import By

from app.tests.base import BaseSeleniumTestCase
from app.tests.constants import USERNAME_USER_DEFAULT, PASSWORD_USER_DEFAULT
from app.tests.utils import create_user, delete_user


class TestPlayaudiomixer(BaseSeleniumTestCase):
    def setUp(self):
        create_user()
        super(TestPlayaudiomixer, self).setUp()
        self.do_login()

    def do_login(self):
        self.driver.get("http://localhost:8080/")
        self.driver.set_window_size(1382, 744)
        self.driver.find_element(By.CSS_SELECTOR, ".btn-secondary").click()
        self.driver.find_element(By.ID, "id_username").click()
        self.driver.find_element(By.ID, "id_username").send_keys(USERNAME_USER_DEFAULT)
        self.driver.find_element(By.ID, "id_password").send_keys(PASSWORD_USER_DEFAULT)
        self.driver.find_element(By.CSS_SELECTOR, ".btn-success").click()
        time.sleep(1)
        self.driver.find_element(By.CSS_SELECTOR, ".popover-navigation > .btn").click()
        self.driver.find_element(By.CSS_SELECTOR, ".jumbotron").click()

    def tearDown(self) -> None:
        delete_user(USERNAME_USER_DEFAULT)
        super(TestPlayaudiomixer, self).tearDown()

    def test_playaudiomixer(self):
        pass
        # time.sleep(1)
        # TODO: Criar uma Track com Mix and File p este user
        # elements = self.driver.find_elements(By.CSS_SELECTOR, ".fa-play")
        # assert len(elements) > 0
        # self.driver.find_element(By.CSS_SELECTOR, ".fa-play").click()
        # self.driver.find_element(By.CSS_SELECTOR, ".modal-title").click()
        # assert self.driver.find_element(By.CSS_SELECTOR, ".modal-text").text == "Loading ..."
        # self.driver.find_element(By.CSS_SELECTOR, ".fa-close").click()
        # self.driver.find_element(By.LINK_TEXT, "Voltar").click()
        # self.driver.find_element(By.LINK_TEXT, "Mixer").click()
        # self.driver.find_element(By.CSS_SELECTOR, ".modal-title").click()
        # elements = self.driver.find_elements(By.CSS_SELECTOR, ".modal-text")
        # assert len(elements) > 0
        # self.driver.find_element(By.CSS_SELECTOR, ".fa-close").click()
        # self.driver.find_element(By.LINK_TEXT, "Inicio").click()
