# Generated by Selenium IDE
import time

from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait

from app.models import Avaliacao
from app.tests.base import BaseLoggedSeleniumTestCase
from app.tests.constants import USERNAME_USER_DEFAULT, NAME_USER_DEFAULT


class TestAvaliacao(BaseLoggedSeleniumTestCase):

    def tearDown(self) -> None:
        Avaliacao.objects.all().delete()
        super(TestAvaliacao, self).tearDown()

    def test_avaliacao_page(self):
        self.driver.find_element(By.LINK_TEXT, "Avalie-nos").click()
        self.driver.find_element(By.ID, "id_username").click()
        value = self.driver.find_element(By.ID, "id_username").get_attribute("value")
        assert value == USERNAME_USER_DEFAULT
        self.driver.find_element(By.ID, "id_first_name").click()
        value = self.driver.find_element(By.ID, "id_first_name").get_attribute("value")
        assert value == NAME_USER_DEFAULT
        self.driver.find_element(By.CSS_SELECTOR, ".min-slider-handle").click()
        time.sleep(2)
        self.driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        self.driver.find_element(By.ID, "id_message").click()
        self.driver.find_element(By.ID, "id_message").send_keys("Tá bom !")
        elements = self.driver.find_elements(By.ID, "alterar")
        assert len(elements) > 0
        elements = self.driver.find_elements(By.LINK_TEXT, "Voltar")
        assert len(elements) > 0
        self.driver.find_element(By.ID, "alterar").click()
        WebDriverWait(self.driver, 30).until(
            expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "h2:nth-child(6)")))
        self.driver.find_element(By.CSS_SELECTOR, "h2:nth-child(6)").click()
        assert self.driver.find_element(By.CSS_SELECTOR, "h2:nth-child(6)").text == "Sucesso"
        self.driver.find_element(By.CSS_SELECTOR, ".sweet-alert").click()
        assert self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(7)").text == "Avaliação enviada com sucesso"
        self.driver.find_element(By.CSS_SELECTOR, ".confirm").click()
